GET http://localhost:3001/api/persons


###
GET http://localhost:3001/api/persons/628bd694829d56af9f3ae578

###
DELETE http://localhost:3001/api/persons/628bda4289572e7dec70e805

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Jimmy Dean",
  "number": "12312412321"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Duplicate User",
  "number": "12312412321"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Missing fields"
}

###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
  "name": "Change Me",
  "number": 27
}

###
PUT http://localhost:3001/api/persons/38
Content-Type: application/json

{
  "name": "Change Me",
  "number": "7"
}

